### PR TITLE
Fix saga

### LINKED ISSUE #13: Recreate sysdata.rda from first principles
See if we can recreate the generation of `R/sysdata.rda` with a script + data in `data-raw` (https://github.com/ninoxconsulting/PEMprepr/pull/7#discussion_r1772048052). Would require access to original data in raw form

### PR DESCRIPTION
**Pull request by gcperk**
This branch was largely an update of saga scripts (landscape and model covars) to streamline and remove the unwanted sysdata.rda and external data files. 
I added two internal check function to connect to saga (find_saga_path() and check_saga().  These are currently internal, however they might need to be fully documented as the reference within the create_covariates link is showing up as a Warning?
```<html>
<body>
<!--StartFragment-->
❯ checking Rd cross-references ... WARNING   Missing link or links in documentation object 'create_covariates.Rd':     'find_saga_path'      Missing link or links in documentation object 'create_samplr_covariates.Rd':     'find_saga_path'      See section 'Cross-references' in the 'Writing R Extensions' manual.  0 errors ✔ \| 1 warning ✖ \| 0 notes ✔
--
 
> | >
>

<!--EndFragment-->
</body>
</html>

 ```
This pull request will close #13 . 

I added basic test functionality, but interested on your assessment to add a snapshot to test running the entire suite of outputs. 
I also suspect the internal point to a local .saga exe is causing the tests to fail, so commenting out for now. Is there a nice way to deal with this? 
ie avoid: sp <- "C:/Programs/saga-9.2.0_x64/saga-9.2.0_x64/saga_cmd.exe" within the testing.

Happy to get your views on overall functionality and any improvements .

### CODE REVIEW

**Comment by gcperk** [comment]
@ateucher - I think this is ready for review, before I get too far down the track. It is throwing an apple/mac error still but everything else is passing. Happy to chat first if that is easier. 
Thanks!

**Comment by ateucher** [comment]
Thanks @gcperk! I've started figuring out how to install on a Mac - notes here: https://github.com/ninoxconsulting/PEMprepr/issues/10#issuecomment-2455955103. I think I'm almost there and can then test this :)

Also in that comment is a link to install it on Linux, so we could do that in GitHub actions and test conditionally there...

**Comment by gcperk** [comment]
thanks @ateucher. I'm not totally clear how much of the setup is required to get the tests to successfully run? Do you need anything from me at the moment?

File: tests/testthat/test-create_landscape_covariates.R [hunk 1]
```diff
@@ -0,0 +1,12 @@
+# test_that("create_landscape_covariates fails with invalid input", {
+#
+#   outdir <- withr::local_tempdir()
+#   sp <- "C:/Programs/saga-9.2.0_x64/saga-9.2.0_x64/saga_cmd.exe"
+#   aoi_snapped <- make_test_aoi(outdir)
+#   aoi_rast <- create_template_raster(aoi_snapped, res = 50, out_dir = outdir)
```
Comment (ateucher) [inline tests/testthat/test-create_landscape_covariates.R:6]: I think these arguments need to be updated: aoi -> dtm

File: tests/testthat/test-create_landscape_covariates.R [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+#
+#   expect_error(create_landscape_covariates(aoi = 1, saga_path = sp))
+#   expect_error(create_landscape_covariates(aoi =  aoi_rast , saga_path = NULL))
+#
+# })
+
```
Comment (ateucher) [inline tests/testthat/test-create_landscape_covariates.R:12]: I know they're not actually running yet, but some tests to test the functionality will be necessary I think (i.e., not just errors)

File: R/create_landscape_covariates.R [hunk 3]
```diff
@@ -0,0 +1,345 @@
...
+    middle.slp <- (tp > -0.5 & tp < 0.5) & (slp > 5)
+    middle.slp[stats::na.omit(middle.slp)] <- 4
+
+    upper.slp <- (tp > 0.5 & tp <= 1)
+    upper.slp[stats::na.omit(upper.slp)] <- 5
+
+    ridge <- (tp > 1)
+    ridge[stats::na.omit(ridge)] <- 6
+
+    # plot(valley, main="Valley", sub="TPI <= -1", cex.main=0.9, cex.sub=0.7, legend=FALSE)
```
Comment (ateucher) [inline R/create_landscape_covariates.R:284]: At some point it would be good to move this commented code out of here and into a script in a `scratch` folder or something like that, it makes it a bit hard to navigate...

File: R/create_landscape_covariates.R [hunk 4]
```diff
@@ -0,0 +1,345 @@
...
+  if (!is.null(saga_path)) {
+    check_saga(saga_path)
+    cli::cli_alert_success(
+      "Your SAGA connection has been succesfuly set up. Using the {.var {saga_path}}"
+    )
+  } else {
+    check_saga()
+    cli::cli_abort("{.var saga_path} must point to the saga_path location on your computer.
+                   Please check your program files or equivalent to locate the saga_path.exe file")
+  }
```
Comment (ateucher) [inline R/create_landscape_covariates.R:81]: I think this can be greatly condensed, since this logic is already in `check_saga()`

```suggestion
check_saga(saga_path)
```

Comment (ateucher) [reply R/create_landscape_covariates.R:81]: Ditto for the same code in `create_covariates()`

File: R/create_covariates.R [hunk 5]
```diff
@@ -1,217 +1,189 @@
...
-  #  out_dir = PEMprepr::read_fid()$dir_1020_covariates$path_rel
-  #  layers = "all"
-  #  # end testing
+  # saga_path = "C:/Program Files/SAGA/saga-9.2.0_x64/saga-9.2.0_x64/saga_path.exe"
+  # out_dir = PEMprepr::read_fid()$dir_1020_covariates$path_rel
+  # layers = "all"
+  # tile = FALSE
 
+  moddir <- fs::path_package("PEMprepr", "extdata/saga_module_depends.csv")
+  # moddir <- read.csv("saga_module_depends.csv")
```
Comment (ateucher) [inline R/create_covariates.R:45]:
```suggestion
  moddir <- read.csv(fs::path_package("PEMprepr", "extdata/saga_module_depends.csv"))
```

Line 118 currently calling `filter()` on a file path, need `read.csv()`

File: R/create_covariates.R [hunk 6]
```diff
@@ -1,217 +1,189 @@
...
+  rn <- terra::res(dtm)[1]
 
 
-  # this is old code which is causing issues with the space in the "program files"
+  #--- SAGA ---#
 
-  if(Sys.info()['sysname']=="Windows"){
-    saga_cmd <- file.path(saga_path, "saga_cmd.exe")
-    fns      <- "\\" ### file name separator
+  if (!is.null(saga_path)) {
```
Comment (ateucher) [inline R/create_covariates.R:65]: Ditto below - can replace L65-74 with `check_saga()`

**Review by ateucher — COMMENTED** [review]
Looking good! Not a full review yet, but `create_covariates()` and `create_landscape_covariates()` are very long, with some bits that seem like they repeat similar patterns, similar to `create_base_vectors()`.

A few comments inline for now; I'm going to work on some infrastructure to detect and use SAGA in different situations...

File: tests/testthat/test-create_landscape_covariates.R (hunk 2 above)
Comment (ateucher) [reply tests/testthat/test-create_landscape_covariates.R:12]: You could even just put them in as placeholders for now until we get the SAGA detection working

**Comment by gcperk** [comment]
Great thanks @ateucher, we completely agree they are long!! I will wait til you are finished with the entire review before I make any changes. A major challenge I have is with the testing as it relies on the saga_path so could see that being an issue. Any ideas there? Thanks for the review as always.

File: inst/extdata/saga_module_depends.csv [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+14,multiresflatness3,,,TRUE
+15,tri,,,
+16,convergence,,,
+17,openness,,,
+18,dah,,,
+19,tpi,,,
+20,ridgevalley,sinksfilled,,
+21,mrn,sinksfilled,,
+22,flowaccumulation,sinksfilled,,TRUE
+23,flowaccumulation,sinksfilled,,TRUE
```
Comment (ateucher) [inline inst/extdata/saga_module_depends.csv:24]: @gcperk are these rows meant to be duplicated?

File: R/create_covariates.R [hunk 8]
```diff
@@ -1,217 +1,189 @@
...
-    print(err.layers)
-    stop("Specified covariates are not a valid options" )
+
+  # check which modules to run and appropriate dependants are also run in order
+  moddirs <- dplyr::filter(moddir, stringr::str_detect(moddir$module, paste(layers, collapse = "|")))
+  mods <- moddirs$module
+  deps <- setdiff(unique(c(moddirs$dep1, moddirs$dep2)), moddirs$module)
+  deps <- deps[!grepl("^\\s*$", deps)]
+  if (length(deps > 0)) {
+    mods <- c(moddir$module, deps)
```
Comment (ateucher) [inline R/create_covariates.R:123]: Should this be `moddirs`, i.e., the filtered data frame? I think so...

```suggestion
    mods <- c(moddirs$module, deps)
```

File: R/create_covariates.R [hunk 9]
```diff
@@ -1,217 +1,189 @@
...
 
-    stop(paste0("`layers` must be type character."), call. = FALSE)
 
+  if (!inherits(layers, "character")) {
+    cli::cli_abort("{.var layers} must be a character string of the names of variables")
   }
 
   if (isTRUE(layers == "all")) {
     layers <- layer_options
   }
```
Comment (ateucher) [inline R/create_covariates.R:107]:
```suggestion
  if (isTRUE(layers == "all")) {
    layers <- layer_options
  } else {
    layers <- c("dem_preproc", layers)
  }
```

Comment (ateucher) [reply R/create_covariates.R:107]: This would be adding dem_preproc, as it seems to be an unstated prerequisite for many

File: R/create_covariates.R [hunk 10]
```diff
@@ -1,217 +1,189 @@
...
+  mods <- moddirs$module
+  deps <- setdiff(unique(c(moddirs$dep1, moddirs$dep2)), moddirs$module)
+  deps <- deps[!grepl("^\\s*$", deps)]
+  if (length(deps > 0)) {
+    mods <- c(moddir$module, deps)
   }
 
 
+  # order the modules to be run
+  layers_to_call <- mods[order(match(mods, moddir$module))]
```
Comment (ateucher) [inline R/create_covariates.R:128]: I got duplicates in some cases

```suggestion
  layers_to_call <- unique(mods[order(match(mods, moddir$module))])
```

File: R/create_covariates.R [hunk 11]
```diff
@@ -1,217 +1,189 @@
...
-#' trim <- terra::rast(trim_raw)
-#' dtm <- terra::project(trim, t25)
-#' tmp <- tempfile(fileext = ".tif")
-#' writeRaster(dtm, tmp)
-#'
-#'
 #' #--- create all SAGA covariates ---#
-#' create_covariates(dtm = tmp, layers = "all", output = dir, SAGApath = SAGApath)
+#' create_covariates(
+#'   dtm = fs::path(PEMprepr::read_fid()$dir_1020_covariates$path_rel,"25m","dem.tif",
```
Comment (ateucher) [inline R/create_covariates.R:25]:
```suggestion
#'   dtm = fs::path(PEMprepr::read_fid()$dir_1020_covariates$path_rel,"25m","dem.tif"),
```

File: tests/testthat/test-create_landscape_covariates.R (hunk 1 above)
Comment (gcperk) [reply tests/testthat/test-create_landscape_covariates.R:6]: thanks - I updated these and added a placeholder for correct working function output

File: R/create_covariates.R (hunk 5 above)
Comment (gcperk) [reply R/create_covariates.R:45]: Shifted this to line 118

File: inst/extdata/saga_module_depends.csv (hunk 7 above)
Comment (gcperk) [reply inst/extdata/saga_module_depends.csv:24]: Yes - I deleted one row

**Comment by gcperk** [comment]
Thanks @ateucher for the review. I updated the create_covariates to update default dem to sinksfilled and updates the csv alongside. I incorporated the minor fixes you found (thanks!). I will now merge back to main so that leaves the saga backend fix which you have on a separate branch.

**Comment by ateucher** [comment]
That's perfect, thanks @gcperk - looks good!
